### ISSUE TITLE
Module identifier replacement

### ISSUE THREAD

**Issue by mrjones2014** [numToStr/lemmy-help#1]
Context: I set up modules like so:

```lua
local M = {}

-- add stuff to M
-- like:
function M.something()
    print('something')
end

return M
```

So when I run the CLI on it, it outputs like:

```
M.something()                                          *M.something*
```

Would there be a way to replace the text `M` in this case with `require('module.path')` for clarity? Could be a simple regex replace or something?

I guess my question is, what's the best way to generate full API docs spread across multiple modules? For context, I'm trying to generate API docs for my legendary.nvim plugin (issue here: https://github.com/mrjones2014/legendary.nvim/issues/106)

**Comment by numToStr** [comment]
For now, there is no option to override this in the CLI but you can use `---@brief` to describe your module and `---@tag` for adding alternate tags.

---

That being said, I am fully aware of this situation and willing to work on improving the doc generation. How about a `---@prefix` tag to override that while generation? Like, for the following lua code

```lua
---@prefix awesome-module

local U = {}

---Add two integar and print it
---@param this number First number
---@param that number Second number
function U.sum(this, that)
	print(this + that)
end

return U
```

This is how it looks currently

```
U.sum({this}, {that})                                                    *U.sum*
    Add two integar and print it

    Parameters: ~
        {this}  (number)   First number
        {that}  (number)   Second number
```

After adding `---@prefix awesome-module`

```
U.sum({this}, {that})                                        *awesome-module-sum*
    Add two integar and print it

    Parameters: ~
        {this}  (number)   First number
        {that}  (number)   Second number
```

**Comment by mrjones2014** [comment]
`---@prefix` sounds perfect.

I think if it also added a heading with an anchor on the heading, that would be a big improvement for documenting multiple modules, does that make sense? So that the docs for different modules have a heading for each module that you can jump to, and they're visually separated a bit.

Would it be possible to replace the `U` on the left as well, e.g. in the `U.sum({this}, {that})`?

**Comment by numToStr** [comment]
> Would it be possible to replace the U on the left as well, e.g. in the U.sum({this}, {that})?

This doesn't matter that much, we can better left it that way. Also remember 80 char width limit :)

> I think if it also added a heading with an anchor on the heading, that would be a big improvement for documenting multiple modules, does that make sense? So that the docs for different modules have a heading for each module that you can jump to, and they're visually separated a bit.

Like you want some kind of separator `====` or `----` to separate modules? If yes, then I'll be there in next release.

Also regarding module, I have two tags in mind with their own use-cases

- `---@prefix <tag>` - Just change the prefix as I shown above.
- `---@module <tag> <desc>` - Will render like the following

```
================================================================================
Awesome description                                                *awesome-tag*
```

**Comment by mrjones2014** [comment]
>Like you want some kind of separator ==== or ---- to separate modules? If yes, then I'll be there in next release.
>
>Also regarding module, I have two tags in mind with their own use-cases
>
> `---@prefix <tag>` - Just change the prefix as I shown above.
> `---@module <tag> <desc>` - Will render like the following

That sounds perfect!

**Comment by mrjones2014** [comment]
Yeah I think `---@module` will cover my use case well enough.

**Comment by numToStr** [comment]
> I'd personally say that `@prefix` is redundant if `@module` is specified

Yeah, I was also thinking the same. So, I could just add `@module` and  clearly describe its behaviour.

**Comment by mrjones2014** [comment]
Perfect. This is gonna be awesome to add API docs for my plugin.

**Comment by numToStr** [comment]
Hmmm...LLS is not happy with me using `---@module` tag XD

![image](https://user-images.githubusercontent.com/24727447/164501629-b5e7b706-2a30-4a3a-823f-3908006ffca0.png)

---

But as it turns out, LLS already reserved the [`---@module`](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#module) tag and it has a specific syntax

Although we can still use it like `---@module 'awesome-module' Awesome module description` but I am not sure how it's going to affect the LSP or actual workflow 🤔

**Comment by mrjones2014** [comment]
I think `---@module 'awesome-module' Awesome module description` should be fine, it's describing a module. This tool would be using it for _almost_ the same purpose.

**Comment by numToStr** [comment]
But what I understand from the LLS docs is you are allowed to define `---@module` multiple times. But here it is only necessary to define it once. 

And I certainly don't want to interfere with LLS and its working. Alternate could be like `---@mod` or something.
