### ISSUE TITLE
Ability to inline class definition in generated docs

### ISSUE THREAD

**Issue by mfussenegger** [numToStr/lemmy-help#20]
First of all thanks for the great tool. Some of my plugins still wouldn't have a API reference documentation without it :)

In lua it is common to use a `opts` table as parameter to mirror keyword arguments. One can document those via `@param opts table|nil [comment]` but with lua-language-server it's more useful to introduce some kind of class to have better code assistance:

```
@class OptsForFunctionXY
@field foo string

...


@param opts OptsForFunctionXY|nil
```

This ends up cluttering the documentation a bit and results in lots of additional tags. See https://github.com/mfussenegger/nvim-jdtls/pull/290/files for an example.

It would be nice if it were possible to inline the options. Instead of:

```
M.build_projects({opts})                                  *jdtls.build_projects*
     Trigger a rebuild of one or more projects.



    Parameters: ~
        {opts}  (JdtBuildProjectOpts|nil)  optional configuration options


JdtBuildProjectOpts                                        *JdtBuildProjectOpts*


    Fields: ~
        {select_mode}  (JdtProjectSelectMode)  Show prompt to select projects or select all. Defaults to "prompt"
        {full_build}   (boolean)               full rebuild or incremental build. Defaults to true (full build)
```

It would generate something like this:

```
M.build_projects({opts})                                  *jdtls.build_projects*
     Trigger a rebuild of one or more projects.



    Parameters: ~
        {opts}  (table|nil)  optional configuration options:
                               * select_mode: (JdtProjectSelectMode) Show prompt
                                  to select projects or select all. Defaults
                                  to "prompt"
                               * full_build: (boolean) full rebuild or
                                  incremental build. Defaults to true (full build)
```

**Comment by numToStr** [comment]
Yeah, I am also thinking about the same for a while. First we need to check if there is any compatibility issue with multi line description with LLS.

And the other limitation comes from the library that I am using to render the aligned structure, currently it doesn't support multiple lines on the last column.

I also want this, so I'll soon start working on this :)

**Comment by numToStr** [comment]
> First we need to check if there is any compatibility issue with multi line description with LLS.

I checked and it seems the following neither shows up in param's hover docs nor produces any errors with LLS

```lua
---Trigger a rebuild of one or more projects.
---@param opts table|nil optional configuration options:
---                        * select_mode: (JdtProjectSelectMode) Show prompt
---                           to select projects or select all. Defaults
---                           to "prompt"
---                        * full_build: (boolean) full rebuild or
---                           incremental build. Defaults to true (full build)
---@param reserverd table|nil reserved for the future use
---@return boolean
function U.build_projects(opts, reserverd)
    return true
end
```

Now I just need to figure out how to render it nicely and aligned with the rest.
