### ISSUE TITLE
Walk directories recursively for files

### ISSUE THREAD

**Issue by Julian** [numToStr/lemmy-help#3]
(Hello! Thanks a ton for investing in writing this kind of thing, it's sorely needed. Hope you don't mind me filing a few minor issues as I try to use it, feel free to close any that aren't planned or helpful obviously, just documenting what I find!)

When running `lemmy-help myplugin/lua/`, expecting it to recurse and generate docs for everything it finds, instead one gets a panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', src/cli.rs:26:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      ~/Desktop/lemmy-help lua/
```

**Comment by numToStr** [comment]
Nope, It is not supported. And I don't think this will be of any use because while generating docs, the order of docs matters and someone might want to also customize the order. So with reading a directory that order is not certain and you'll loose the the ability to customize the order.

**Comment by Julian** [comment]
Fair enough. One could just use say, alphabetical? But if not maybe it's at least worth changing the panic to an error?

**Comment by numToStr** [comment]
Sure, I am soon going to work on error handling for the whole CLI and the crate.
