### ISSUE TITLE
README install instruction errors

### ISSUE THREAD

**Issue by Julian** [numToStr/lemmy-help#4]
Running the install command from the readme:

```
cargo install lemmy-help --features=cli
```

here (macOS M1, arm64 `cargo` 1.59.0 installed via homebrew) yields:

```
⊙  cargo install lemmy-help --features=cli                                                                                                                                          julian@Airm
    Updating crates.io index
  Downloaded lemmy-help v0.0.0
  Downloaded 1 crate (7.8 KB) in 0.47s
  Installing lemmy-help v0.0.0
error: failed to compile `lemmy-help v0.0.0`, intermediate artifacts can be found at `/var/folders/4p/mgyph8ds28sgxk21xrn2f5r80000gn/T/cargo-installNS7zVy`
```

which looks like it's finding a release older than the one here on GitHub perhaps. (Not sure if that's just a timing issue and cargo hasn't seen the new release yet? If so obviously close).

**Comment by numToStr** [comment]
For me, cargo fetches the 0.0.1. It might be because the MSRV is 1.60.0 and you happen to have 1.59.0(?)

**Comment by numToStr** [comment]
I am going to close this as I think it's more of cargo/rust quirk.
