### ISSUE TITLE
Better support for nested types

### ISSUE THREAD

**Issue by aspeddro** [numToStr/lemmy-help#46]
```lua
---Arguments
---@type table<string, string|table<string>>
M.types = {
  ["--wrap"] = { "auto", "none", "preserve" },
  ["--ascii"] = "flag",
}
```

Output:

```vim
M.types                                                                *M.types*
    Arguments

    Type: ~
        (table<string,)  string|table<string>>

```

Another case: `table<string, string[]|string>`

**Comment by numToStr** [comment]
This is actually on my to-do list #27.

(As a workaround just remove the whitespace between the key and the value)

**Comment by numToStr** [comment]
FYI, this `table<string, string|table<string>>` syntax is invalid and will be skipped by the parser.

The correct annotations is `table<string, string|string[]>`, if you need array of string.
