### ISSUE TITLE
whitespace handling in function type signature

### ISSUE THREAD

**Issue by mfussenegger** [numToStr/lemmy-help#48]
lua-language-server allows to define the type for functions like `fun(PARAM: TYPE): RETURN_TYPE`

It appears that lemmy-help currently stops at the first whitespace.

In something like this:

```
---@alias TestRunner fun(classname: string, methodname: string):string, string[]
```

It only renders:

```
     Type: ~
         fun(classname:
```

Without whitespace it works:

```
---@alias TestRunner fun(classname:string,methodname:string):(string,string[])
```

Would be nice if the variant with whitespaces worked too.

*Update*: I just noticed https://github.com/numToStr/lemmy-help/pull/47, so this is already getting addressed?

**Comment by numToStr** [comment]
Yup, most types will be parsed correctly after #47. Although after seeing your example I might also need to handle multiple returns 🙂
