### ISSUE TITLE
Private field makes a field a public function

### ISSUE THREAD

**Issue by tversteeg** [numToStr/lemmy-help#53]
I'm trying to switch to 0.8.0, but I have the following issue, I have a class with the following:

```lua
---@class registers
---@field options options
---@field private _mode string
```

When I generate the documentation, I get this:

```help
registers._mode()                                              *registers._mode*
```

**Comment by numToStr** [comment]
lemmy-help doesn't walk the AST to check private fields. It just doesn't render `---@field private ....` in vimdoc.

Use [`---@private`](https://github.com/numToStr/lemmy-help/blob/master/emmylua.md#private) to prevent any lua code from appearing in vimdoc.

**Comment by tversteeg** [comment]
That's what I want, to not render the private fields in the doc, but unfortunately they still get rendered.

**Comment by numToStr** [comment]
Could provide the lua code? So, I can check for myself.

**Comment by tversteeg** [comment]
Here it is: https://github.com/tversteeg/registers.nvim/blob/preview/lua/registers.lua#L33

**Comment by numToStr** [comment]
Looking at the file, it seems you've defined `---@private` as the last annotation, which is wrong.

```lua
---Get the register information matching the register.
---@param register? string Register to look up, if nothing is passed the current line will be used
---@return? table Register information from `registers._register_values`
---@private
function registers._register_info(register) end
```

Instead write `---@private` as the first annotation.

```lua
---@private
---Get the register information matching the register.
---@param register? string Register to look up, if nothing is passed the current line will be used
---@return? table Register information from `registers._register_values`
function registers._register_info(register) end
```

---

OTOH, I am curious as to why do you need to define the `registers` class, it seems redundant to me.

**Comment by tversteeg** [comment]
I've put all the `---@private` as the first annotation, as you suggested, but that doesn't fix the issue.

> OTOH, I am curious as to why do you need to define the registers class, it seems redundant to me.

I would like to add type checks to the module. Is there a better way to do this?

**Comment by numToStr** [comment]
> I've put all the `---@private` as the first annotation, as you suggested, but that doesn't fix the issue.

Working for me though. As you can see `registers._register_info` is missing from the output.

![image](https://user-images.githubusercontent.com/24727447/196133484-ea872b79-e827-4dbf-8b88-1ad4f1f6095b.png)


> I would like to add type checks to the module. Is there a better way to do this?

Hmmm...If type-checking is the reason, then I guess it's fine.

**Comment by tversteeg** [comment]
But the methods aren't the problem, it's the fields that are shown as method.

```lua
---@field private _mode string
```

**Comment by numToStr** [comment]
Alright, finally reproduced the issue and it is completely unrelated to private thingy.

This

```lua
local M = {}

M._mode = 124

return M
```

renders as

```help
M._mode()                                                              *M._mode*
```

So, the issue is `()` is added is added in tag's title for expressions.

**Comment by tversteeg** [comment]
But the `---@field private` part is also ignored, since it shouldn't show up at all.

**Comment by numToStr** [comment]
Yes, and it seem 3fc909ee00aded845f822ae011579b2d59709238 is the culprit. Because with 0.7 that code renders nothing, which is correct behavior. So, I might have to revert that.

**Comment by numToStr** [comment]
Released https://github.com/numToStr/lemmy-help/releases/tag/v0.8.1
