### ISSUE TITLE
Regression on parsing vararg param (...)

### ISSUE THREAD

**Issue by rmagatti** [numToStr/lemmy-help#61]
Hi 👋 

There seems to be a regression I'm not sure is intentional or not when parsing a vararg parameter.

Example:
```lua
---DeleteSessionByName deletes sessions given a provided list of paths
---@param ... string[]
function AutoSession.DeleteSessionByName(...)
  local session_paths = {}

  for _, name in ipairs { ... } do
    local escaped_session = Lib.escape_dir(name)
    maybe_disable_autosave(escaped_session)
    local session_path = string.format("%s/%s.vim", AutoSession.get_root_dir(), escaped_session)
    Lib.logger.debug("Deleting session", session_path)
    table.insert(session_paths, session_path)
  end
  AutoSession.DeleteSession(unpack(session_paths))
end
```
Found in:
https://github.com/rmagatti/auto-session/blob/609c952a50ff1d415d79323364e934eba607fce0/lua/auto-session.lua#L613

Parses to:
https://github.com/rmagatti/auto-session/pull/182/files#diff-27d42bba8f6f0166fc94265a6b8117318675825157368bc590c0da01ba3cba94R145

Instead of:
https://github.com/rmagatti/auto-session/pull/182/files#diff-27d42bba8f6f0166fc94265a6b8117318675825157368bc590c0da01ba3cba94L153

<img width="756" alt="Screenshot 2022-11-16 at 9 46 22 PM" src="https://user-images.githubusercontent.com/2881382/202358433-0461fe14-904b-458c-b74c-0f55f87198de.png">

**Comment by numToStr** [comment]
Ohh, I completely forgot to parse vararg in #47. Thanks for reporting the bug! I'll fix it.

**Comment by rmagatti** [comment]
Oh damn, that was fast! I'm assuming I should wait for a .tgz version of the lib to try it out? Thanks again!

**Comment by numToStr** [comment]
Yeah, I release next version in couple of days as I am thinking of squeezing #58 in the next release.
