### ISSUE TITLE
Literal values in the type definition lead to empty docs

### ISSUE THREAD

**Issue by mfussenegger** [numToStr/lemmy-help#69]
lua-language-server supports defining literals/an sum type inline in the type definition. An example: `@param x "foo"|"bar"`

But this seems to break lemmy-help:

```lua
local M = {}

--- Foobar
---@param t? "foo"|"bar"
function M.foo(t)
  print(t)
end

return M
```

Results in:

```
❮ lemmy-help -f foo.lua
M.foo()                                                                  *M.foo*


vim:tw=78:ts=8:noet:ft=help:norl:
```

![image](https://user-images.githubusercontent.com/38700/207422178-400e13b0-b264-4a27-bdf9-da3fd9557df8.png)

Compared with a regular type definition:

```lua
local M = {}

--- Foobar
---@param t? string
function M.foo(t)
  print(t)
end

return M
```

Which works as expected:

```
❮ lemmy-help -f foo.lua
M.foo({t?})                                                              *M.foo*
     Foobar

    Parameters: ~
        {t?}  (string)


vim:tw=78:ts=8:noet:ft=help:norl:
```

The long form also works:

```lua
local M = {}

--- Foobar
---@param t? string
---|"foo"
---|"bar"
function M.foo(t)
  print(t)
end

return M
```

```
❮ lemmy-help -f foo.lua
M.foo({t?})                                                              *M.foo*
     Foobar

    Parameters: ~
        {t?}  (string)  |"foo"
                        |"bar"


vim:tw=78:ts=8:noet:ft=help:norl:
```

**Comment by numToStr** [comment]
Fow now enum variants needs to be wrapped with single quote (`'`) whether it's inline or defined with `----@alias`. This is a constraint that I deliberately put in otherwise I have to parse different constructs.

```lua
---@param t? '"foo"'|'"bar"'
```

```lua
---@alias T
---| '"foo"' # Foo Variant
---| '"bar"' # Bar Variant
```

There is also ``` ` ``` which allows identifiers as variant, but currently is not supported. https://github.com/sumneko/lua-language-server/wiki/Annotations#alias

![image](https://user-images.githubusercontent.com/24727447/207504237-a58948a7-c5a4-4710-b8fa-792bb8bf406e.png)

**Comment by mfussenegger** [comment]
> Fow now enum variants needs to be wrapped with single quote (`'`) whether it's inline or defined with `----@alias`. This is a constraint that I deliberately put in otherwise I have to parse different constructs.
> 
> ```lua
> ---@param t? '"foo"'|'"bar"'
> ```
> 
> ```lua
> ---@alias T
> ---| '"foo"' # Foo Variant
> ---| '"bar"' # Bar Variant
> ```
> 
> There is also `` ` `` which allows identifiers as variant, but currently is not supported. https://github.com/sumneko/lua-language-server/wiki/Annotations#alias
> 
> ![image](https://user-images.githubusercontent.com/24727447/207504703-8ac9c172-86d9-46fc-b6da-1ae8283cc9b1.png)
> 
> ![image](https://user-images.githubusercontent.com/24727447/207504237-a58948a7-c5a4-4710-b8fa-792bb8bf406e.png)

Oh that's good to know. Thanks
