### ISSUE TITLE
Please support `---@version`, `---@author`, `---@license`, `---@created` and `---@lastmod`.

### ISSUE THREAD

**Issue by dharmx** [numToStr/lemmy-help#76]
~~As, shown [here](https://github.com/nvim-telescope/telescope.nvim/blob/203bf5609137600d73e8ed82703d6b0e320a5f36/lua/telescope/themes.lua#L6-L14).~~

Also, being really greedy here! Can you also support `---@version`, `---@author`, `---@license`, `---@created` and `---@lastmod`.
Which means version number, last author name, license name/summary, creation time and last-modified time. Maybe similar to [this](https://github.com/ggandor/leap.nvim/blob/ff4c3663e5a0a0ecbb3fffbc8318825def35d2aa/doc/leap.txt#L1-L3).

Thank you!

**Comment by numToStr** [comment]
`---@tag` and `---@brief` are already supported. Please read the docs.

As for the other tags, it's not a matter of adding them, we also need to take care of how they look and whether they will interfere with lua-language-server.

**Comment by dharmx** [comment]
Oh! I thought it was just a general guide to write emmylua docs. Reading it right now. Should I swap the title of this issue with those other tags then?

**Comment by dharmx** [comment]
Also, I do not know if it has something to do with my settings but writing those tags did not result in any warnings from the language server.

**Comment by numToStr** [comment]
> Should I swap the title of this issue with those other tags then?

It goes without saying.

> writing those tags did not result in any warnings from the language server.

Nice. Although I would suggest you to share how you intend to write those tags on the lua side and how you want your docs to look like. So that we can work with sketches before getting into the implementation.

**Comment by dharmx** [comment]
Alright! I already have some of my files using those tags. I'll get back to you with a minimal example in a bit.

**Comment by dharmx** [comment]
This is a rough specification file for preferences and features that the following
tags should support.

- The `---@license` tag.
- The `---@lastmod` tag.
- The `---@version` tag.
- The `---@created` tag.
- The `---@author` tag.

## The `---@license` tag.

This is also a top level tag like `---@brief`.
This should support taking in one parameter if possible.

- Linking the complete license.

```lua
---@license [[
--- GNU GENERAL PUBLIC LICENSE
--- Version 3, 29 June 2007
---
--- Permissions of this strong copyleft license are conditioned on
--- making available complete source code of licensed works and
--- modifications, which include larger works using a licensed work,
--- under the same license. Copyright and license notices must be
--- preserved. Contributors provide an express grant of patent rights.
--@license ]]
```

This should result in the following.

```vimdoc
*plugin.txt*

GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Permissions of this strong copyleft license are conditioned on
making available complete source code of licensed works and
modifications, which include larger works using a licensed work,
under the same license. Copyright and license notices must be
preserved. Contributors provide an express grant of patent rights.
```

Now, with the link parameter.

```lua
---@license "https://github.com/numToStr/lemmy-help/blob/master/LICENSE" [[
--- GNU GENERAL PUBLIC LICENSE
--- Version 3, 29 June 2007
---
--- Permissions of this strong copyleft license are conditioned on
--- making available complete source code of licensed works and
--- modifications, which include larger works using a licensed work,
--- under the same license. Copyright and license notices must be
--- preserved. Contributors provide an express grant of patent rights.
--@license ]]
```

This should result in the following.

```vimdoc
*plugin.txt*

Licensed under:
GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Permissions of this strong copyleft license are conditioned on
making available complete source code of licensed works and
modifications, which include larger works using a licensed work,
under the same license. Copyright and license notices must be
preserved. Contributors provide an express grant of patent rights.

Read the complete license here:
https://github.com/numToStr/lemmy-help/blob/master/LICENSE
```

Also note that this should have a higher priority than `---@brief`.

## The `---@author` tag.

This is also another top level tag like `---@brief` and `---@mod` i.e.
only allow this at the very top of the file.
This should be ranked above the `---@license` tag.

Now, look at the following demo.

```lua
---@author dharmx | dharmx.dev@gmail.com

---@mod sample THIS IS A SAMPLE

---@brief [[
---A very, very short overview of this module.
---@brief ]]
```

This should be rendered to the following.

```vimdoc
Authored by: dharmx | dharmx.dev@gmail.com

==============================================================================
THIS IS A SAMPLE                                                           *sample*

A very, very short overview of this module.
```

### Additional Note

It would be nice if we could disable the horizontal line that comes with `---@mod` and
a way to align `*sample*` to the very left **if** `<name>` is empty. Hence, see the
following.

```lua
---@mod false noalign sample.txt

---@author dharmx | dharmx.dev@gmail.com
```

Here, `false` should indicate if the horizontal line should be added and `noalign` should
press to the very left. See the following.

```vimdoc
*sample.txt*
Authored by: dharmx | dharmx.dev@gmail.com
```

This way we can have the ranking of `---@mod` higher than that of `---@author`. Well, perhaps
we could have a different tag for this.

## The `---@lastmod`, `---@created` and `---@version` tags.

These should have the same ranking and should be lower than `---@author`. Now, see the following
sample.

```lua
---@author dharmx | dharmx.dev@gmail.com
---@created 2022-11-18
---@lastmod 2022-11-19
---@version 0.1.0
```

This should be rendered into the following.

```vimdoc
Authored by: dharmx | dharmx.dev@gmail.com
Creation date: 2022 November 18
Last modified: 2022 November 19
Version: 0.1.0
```

## A full sample.

```lua
-- vim:filetype=lua

---@author dharmx | dharmx.dev@gmail.com
---@created 2022-11-18
---@lastmod 2022-11-19
---@version 0.1.0

---@mod sample A SAMPLE MODULE

---@license "https://github.com/numToStr/lemmy-help/blob/master/LICENSE" [[
--- GNU GENERAL PUBLIC LICENSE
--- Version 3, 29 June 2007
---
--- Permissions of this strong copyleft license are conditioned on
--- making available complete source code of licensed works and
--- modifications, which include larger works using a licensed work,
--- under the same license. Copyright and license notices must be
--- preserved. Contributors provide an express grant of patent rights.
--@license ]]

---@brief [[
---Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim 
---labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet.
---Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum
---Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident.
---@brief ]]

---@mod config THE SAMPLE CONFIG

---@class SampleConfig This a configuration table for a sample plugin.
---@field setup boolean The setup function.
---@field load string[] Modules to load.
---@field condition fun(path:string):string|nil A function.

---@type SampleConfig
local Config = {
  ---A Sample option.
  setup = true,
  load = { "core", "plug", "theme" },
  ---This is a condition function.
  ---@param path string
  ---@return string|nil
  condition = function(path) return path:match("load") end,
}

---Setup function.
---@see nvim-dharmx-config
---@usage `require("sample").startup()`
function Config.startup()
  if Config._done then return end
  Config._done = true
end

return Config
```

```vimdoc
Authored by: dharmx | dharmx.dev@gmail.com
Creation date: 2022 November 18
Last modified: 2022 November 19
Version: 0.1.0

Licensed under:
GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Permissions of this strong copyleft license are conditioned on
making available complete source code of licensed works and
modifications, which include larger works using a licensed work,
under the same license. Copyright and license notices must be
preserved. Contributors provide an express grant of patent rights.

Read the complete license here:
https://github.com/numToStr/lemmy-help/blob/master/LICENSE

==============================================================================
A SAMPLE MODULE                                                         *sample*

Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim 
labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet.
Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum
Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident.

==============================================================================
THE SAMPLE CONFIG                                                       *config*

SampleConfig                                               *config.SampleConfig*


Config.startup()                                                *config.startup*
    Setup function.

    See: ~
        |nvim-dharmx-config|

    Usage: ~
>lua
        require("sample").startup()
<


vim:tw=78:ts=8:noet:ft=help:norl:
```

**Comment by dharmx** [comment]
Let me know what you think!

**Comment by numToStr** [comment]
Thanks for the detailed explanation. Even though these looks useful, they certainly don't provide any real benefit and can be easily covered by `---@brief`. That's what I am also using in [Comment.nvim](https://github.com/numToStr/Comment.nvim/blob/eab2c83a0207369900e92783f56990808082eac2/lua/Comment/init.lua#L1-L13). Also, there is no concept of priority. Everything is parsed and rendered from top to bottom. If you go by these rules, your file might look like this.

```lua
-- vim:filetype=lua

---@brief [[
---Authored by: dharmx | dharmx.dev@gmail.com
---Creation date: 2022 November 18
---Last modified: 2022 November 19
---Version: 0.1.0
---
---Licensed under:
---GNU GENERAL PUBLIC LICENSE
---Version 3, 29 June 2007
---
---Permissions of this strong copyleft license are conditioned on
---making available complete source code of licensed works and
---modifications, which include larger works using a licensed work,
---under the same license. Copyright and license notices must be
---preserved. Contributors provide an express grant of patent rights.
---
---Read the complete license here:
---https://github.com/numToStr/lemmy-help/blob/master/LICENSE
---@brief ]]

---@mod sample A SAMPLE MODULE

---@brief [[
---Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim 
---labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet.
---Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum
---Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident.
---@brief ]]

...
```

---

One thing that might somewhat related your request is the [first line](https://github.com/numToStr/Comment.nvim/blob/eab2c83a0207369900e92783f56990808082eac2/doc/Comment.txt#L1) (IDK what this is really called) of the help file. If you have any idea on how it's emmylua should look like, I'll be happy to hear it :)

**Comment by dharmx** [comment]
That seems really neat. I did not know you could use `---@brief` twice! Rather, I did not try using it that way. As, for the first line thing, I think a doctag with two parameters would be great, like `---@headmod <tag-name> <version> <lastmod>` to `---@headmod comment-nvim.txt 0.7 2021-07-11`. And, if you do want to support spaces.. I think enclosing them around `""` would be great.

Also, my issues have been solved! This can be closed if you want.

**Comment by numToStr** [comment]
Thanks for the idea! I'll track the doctag in another issue. Closing this now.
