### ISSUE TITLE
Prefix behaviour is strange

### ISSUE THREAD

**Issue by noriapi** [numToStr/lemmy-help#78]
I found a strange behavior when using the `--prefix` option.

Run `lemmy-help --prefix-alias` on the following code.

```lua
---@mod first-module First module

---@alias first_alias number

---@mod second-module Second module

---@alias second_alias number

local U = {}
return U
```

Then `first-alias` is prefixed with `second-module` even though it is right under `first-module`. This happens whether it is a function, class or type.

```help
==============================================================================
First module                                                      *first-module*

first_alias                                          *second-module.first_alias*

    Type: ~
        number


==============================================================================
Second module                                                    *second-module*

second_alias                                        *second-module.second_alias*

    Type: ~
        number


vim:tw=78:ts=8:noet:ft=help:norl:
```

Is this a bug? If not, how can I prefix `first-alias` with `first-module`?

**Comment by numToStr** [comment]
This is expected behaviour https://github.com/numToStr/lemmy-help/blob/master/emmylua.md#module.

The general recommendation is to use a single `---@mod` per file.

**Comment by noriapi** [comment]
I understand. Thank you for your quick reply!
